config/routes.rb
Rails.application.routes.draw do

  resources :trips

end

  

  #   end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/pack.rb
class Pack < ActiveRecord::Base
end

app/models/trip.rb
class Trip < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

	def index 
		@trips = Pack.all
	end

	def show
		@trip = Trip.find_by(id: params["id"])
	end

  def new
    @trip = Trip.new
  end

  def create
    trip_params = params.require(:trip).permit!
    Trip.create(trip_params)
    redirect_to trips_path
  end

  def edit
    @trip = Trip.find_by(id: params["id"])
  end

  def update
    trip_params = params.require(:trip).permit!
    @trip = Trip.find_by(id: params["id"])
    @trip.update(trip_params)
    redirect_to trips_path
  end

  def destroy
    @trip = Trip.find_by(id: params["id"])
    @trip.destroy
    redirect_to trips_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trips/index.html.erb
<h1>These are all your Packing Lists</h1>

<table class="table">
<% @trips = Trip.all %>

<% @trips.each do |trip| %>
  <tr>
    <td><a href="/trips/<%= trip.id %>"><%= trip.name %> </a></td>
  </tr>
<% end %>

<%= link_to 'Create new trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>Create a New Trip</h1>

<%= form_for @trip do |form| %>
  <div class="form-group">
    <%= form.label :Trip_name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.order(:name), :id, :name, { include_blank: true }, { class: "form-control" } %>
  </div>
    
  <div class="form-group">
    <%= form.label :city_id %>
    <%= form.text_field :city_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :duration_of_trip %> (in days) 
    <%= form.text_field :duration, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :season %>
    <%= form.text_field :season, class: "form-control" %>
  </div>

  <%= form.button 'Create Trip', class: "btn btn-success" %>

<% end %>

app/views/trips/show.html.erb
<h1>Packing List for <%= @trip.name %></h1>

<p>Duration: <%= @trip.duration %> days</p>

<p>Season: <%= @trip.season %></p>